[tool.poetry]
name = "toboggan"
version = "2.1.1"
description = "CLI tool designed to wrap modules for Remote Command Execution (RCE). It enables interactive shell functionality, making it ideal for constrained environments (e.g., firewalls) where establishing a reverse shell is challenging."
authors = ["n3rada"]
license = "MIT license"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
prompt-toolkit = ">=3.0.39"
tqdm = ">=4.66.0"
httpx = ">=0.24.1"
pycryptodome = "^3.20.0"
pyperclip = "^1.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
toboggan = "toboggan.console:run"