[project]
name = "toboggan"
version = "1.0.0"
description = "Bring intelligence to any remote command execution (RCE)."
authors = [
    {name = "n3rada"}
]
license = {text = "GPL-3.0-or-later"}
readme = "README.md"
requires-python = ">=3.11,<4.0"

[project.urls]
repository = "https://github.com/n3rada/toboggan"

[project.scripts]
toboggan = 'toboggan.console:run'

[build-system]
requires = ["poetry-core>=2.1.1,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.dependencies]
prompt-toolkit = "^3.0.50"
httpx = "^0.28.1"
tqdm = "^4.67.1"
